/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package apotik_surya;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author altec
 */
public class transaksi extends javax.swing.JFrame {
//var koneksi
private String sql, sql2;
private Statement st, st2;
private DefaultTableModel dtm;
private ResultSet rs,rs2;    
    /**
     * Creates new form transaksi
     */
    public transaksi() {
        initComponents();
        tampil_combo();
        tampil_tabel();
    }
    public void tampil_tabel ()
    {
    try {
        Object [] rows = {"ID TRANSAKSI", "TANGGAL", "NAMA OBAT", "HARGA OBAT", "JUMLAH BELI", "TOTAL", "DISKON", "TOTAL BAYAR"};
        dtm = new DefaultTableModel(null, rows);
        tabel_tarnsaksi.setModel(dtm);
        
        String idtrans="", tgltrans="", nmobat="", hrgobat="", jmlbeli="", total="", diskon="", totalbayar="";
        try {
            Connection c = koneksiDB.getkoneksi();
            sql = "Select nmobat, hrgobat, idtrans, tgltrans, jmlbeli, total, diskon, totalbayar from obat INNER JOIN transaksi ON obat.kdobat=transaksi.kdobat";
            st = c.createStatement();
            rs = st.executeQuery(sql);
            
                      
            while (rs.next()){
                idtrans = rs.getString("idtrans");
                tgltrans = rs.getString("tgltrans");
                nmobat = rs.getString("nmobat");
                hrgobat = rs.getString("hrgobat");
                jmlbeli = rs.getString("jmlbeli");
                total = rs.getString("total");
                diskon = rs.getString("diskon");
                totalbayar = rs.getString("totalbayar");
                
                String [] tampil = {idtrans, tgltrans,nmobat , hrgobat, jmlbeli, total, diskon, totalbayar};
                dtm.addRow(tampil);
            }           
        } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Query Salah"+e.getMessage());
        }
        
    } catch (Exception e) {}
    }
    public void tampil_combo()
    {       
        try {
        Connection con = koneksiDB.getkoneksi();
        Statement st = con.createStatement();
        String sql = "select kdobat from obat order by kdobat asc";      // disini saya menampilkan NIM, anda dapat menampilkan
        ResultSet res = st.executeQuery(sql);                                // yang anda ingin kan
               
        while(res.next()){
            Object[] ob = new Object[3];
            ob[0] = res.getString(1);
            
            cmbkodeobat.addItem(ob[0]);                                      // fungsi ini bertugas menampung isi dari database
        }
        res.close(); st.close();
         
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }
     public void tampil()
    {
        //disini blum
        try {
        Connection con = koneksiDB.getkoneksi();
        Statement stt = con.createStatement();
        String sql = "select nmobat, hrgobat, stok from obat where kdobat='"+cmbkodeobat.getSelectedItem()+"'";  
        ResultSet res = stt.executeQuery(sql);
        
        while(res.next()){
            Object[] ob = new Object[3];
            ob[0]=  res.getString(1);
            ob[1]=  res.getString(2);
            ob[2]=  res.getString(3);
            
            txtnamaobat.setText((String) ob[0]);
            txthargaobat.setText((String) ob[1]);
            txtstokobat.setText((String) ob[2]);
        }
        res.close(); st.close();
         
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }              
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtidtransaksi = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        txttanggaltarnsaksi = new javax.swing.JTextField();
        txtnamaobat = new javax.swing.JTextField();
        txthargaobat = new javax.swing.JTextField();
        cmbkodeobat = new javax.swing.JComboBox();
        txtstokobat = new javax.swing.JTextField();
        txtjumlahbeli = new javax.swing.JTextField();
        txttotal = new javax.swing.JTextField();
        txtjumlahdiskon = new javax.swing.JTextField();
        txttotalbayar = new javax.swing.JTextField();
        savetransaksi = new javax.swing.JButton();
        gotoobat = new javax.swing.JButton();
        gotomenu = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_tarnsaksi = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("ID Transaksi");

        jLabel2.setText("Tanggal Transaksi");

        jLabel3.setText("Kode Obat");

        jLabel4.setText("Nama Obat");

        jLabel5.setText("Harga Obat");

        jLabel6.setText("Stok Obat");

        jLabel7.setText("Jumlah Beli");

        jLabel8.setText("Total");

        jLabel9.setText("Jumlah Diskon");

        jLabel10.setText("Total Bayar");

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel11.setText("TRANSAKSI");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(712, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(102, 102, 102))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addContainerGap())
        );

        cmbkodeobat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbkodeobatActionPerformed(evt);
            }
        });

        txtjumlahbeli.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtjumlahbeliMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtjumlahbeliMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                txtjumlahbeliMouseReleased(evt);
            }
        });
        txtjumlahbeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtjumlahbeliActionPerformed(evt);
            }
        });

        savetransaksi.setText("SIMPAN");
        savetransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savetransaksiActionPerformed(evt);
            }
        });

        gotoobat.setText("OBAT");
        gotoobat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gotoobatActionPerformed(evt);
            }
        });

        gotomenu.setText("<<");
        gotomenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gotomenuActionPerformed(evt);
            }
        });

        tabel_tarnsaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabel_tarnsaksi);

        jScrollPane2.setViewportView(jScrollPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtidtransaksi)
                    .addComponent(txttanggaltarnsaksi)
                    .addComponent(cmbkodeobat, javax.swing.GroupLayout.Alignment.TRAILING, 0, 197, Short.MAX_VALUE)
                    .addComponent(txtnamaobat)
                    .addComponent(txthargaobat)
                    .addComponent(txtstokobat)
                    .addComponent(txtjumlahbeli)
                    .addComponent(txttotal)
                    .addComponent(txtjumlahdiskon)
                    .addComponent(txttotalbayar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(savetransaksi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(gotoobat)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(gotomenu)
                        .addGap(14, 14, 14))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(txtidtransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(txttanggaltarnsaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabel3))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(cmbkodeobat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(8, 8, 8)
                        .addComponent(jLabel4)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel5)
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(txtstokobat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(txtjumlahbeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txttotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtjumlahdiskon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txttotalbayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtnamaobat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txthargaobat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(savetransaksi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(gotoobat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(gotomenu, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void gotoobatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gotoobatActionPerformed
        obat buka = new obat();
        buka.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_gotoobatActionPerformed

    private void gotomenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gotomenuActionPerformed
        halaman_utama buka = new halaman_utama();
        buka.setVisible(true);
    }//GEN-LAST:event_gotomenuActionPerformed

    private void cmbkodeobatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbkodeobatActionPerformed
        tampil();
    }//GEN-LAST:event_cmbkodeobatActionPerformed

    private void savetransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savetransaksiActionPerformed
        try {
            Integer stokakhir, stokobat, jumlahbeli;
            
            stokobat = Integer.parseInt(txtstokobat.getText());
            jumlahbeli = Integer.parseInt(txtjumlahbeli.getText());
                  
            stokakhir = stokobat - jumlahbeli;
                        
            Connection c = koneksiDB.getkoneksi();
            sql = "insert into transaksi values ('"+txtidtransaksi.getText()+"','"
                                              +txttanggaltarnsaksi.getText()+"','"
                                              +cmbkodeobat.getSelectedItem()+"','"
                                              +txtjumlahbeli.getText()+"','"
                                              +txttotal.getText()+"','"
                                              +txtjumlahdiskon.getText()+"','"
                                              +txttotalbayar.getText()+"')";
            
            sql2 = "update obat set stok = '"+stokakhir+
                                                "' where kdobat = '"+cmbkodeobat.getSelectedItem()+"'";
            
            st = c.createStatement();
            st.executeUpdate(sql);
            
            st2 = c.createStatement();
            st2.executeUpdate(sql2);
            
            JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan","Informasi", JOptionPane.INFORMATION_MESSAGE);
            tampil_tabel();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Data Gagal Disimpan"+e.getMessage());
        }
    }//GEN-LAST:event_savetransaksiActionPerformed

    private void txtjumlahbeliMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtjumlahbeliMousePressed
        
    }//GEN-LAST:event_txtjumlahbeliMousePressed

    private void txtjumlahbeliMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtjumlahbeliMouseEntered
        
    }//GEN-LAST:event_txtjumlahbeliMouseEntered

    private void txtjumlahbeliMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtjumlahbeliMouseReleased
        
    }//GEN-LAST:event_txtjumlahbeliMouseReleased

    private void txtjumlahbeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtjumlahbeliActionPerformed
        Integer jumlahbeli, hargaobat, total, totalbayar, diskon = null;
        String kode_obat;
               
        
        jumlahbeli = Integer.parseInt(txtjumlahbeli.getText());
        hargaobat = Integer.parseInt(txthargaobat.getText());
        kode_obat = (String) cmbkodeobat.getSelectedItem();
        if(kode_obat == "OBT001"){
            diskon =((10 * hargaobat)/100) * jumlahbeli;    
        }else if(kode_obat == "OBT002"){
            diskon =(15 * hargaobat)/100 * jumlahbeli;    
        }else{
            diskon =((20 * hargaobat)/100) * jumlahbeli;  
        }
        //cari total
        total = jumlahbeli * hargaobat;
        totalbayar = (hargaobat * jumlahbeli) - diskon;
        
        String tampildiskon = String.valueOf(diskon);
                 txtjumlahdiskon.setText(tampildiskon);
                 
        String tampiltotalbayar = String.valueOf(totalbayar);
             txttotalbayar.setText(tampiltotalbayar);
             
        String tampiltotal = String.valueOf(total);
             txttotal.setText(tampiltotal);
    }//GEN-LAST:event_txtjumlahbeliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new transaksi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cmbkodeobat;
    private javax.swing.JButton gotomenu;
    private javax.swing.JButton gotoobat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton savetransaksi;
    private javax.swing.JTable tabel_tarnsaksi;
    private javax.swing.JTextField txthargaobat;
    private javax.swing.JTextField txtidtransaksi;
    private javax.swing.JTextField txtjumlahbeli;
    private javax.swing.JTextField txtjumlahdiskon;
    private javax.swing.JTextField txtnamaobat;
    private javax.swing.JTextField txtstokobat;
    private javax.swing.JTextField txttanggaltarnsaksi;
    private javax.swing.JTextField txttotal;
    private javax.swing.JTextField txttotalbayar;
    // End of variables declaration//GEN-END:variables
}
